title: Natural Language Processing
description: A bilingual (English - Arabic) glossary for NLP terminology
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-slate
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
